import Head from "next/head";
import React, { type FC, type ReactNode } from "react";

interface PageHelmetProps {
  title: string;
  children?: ReactNode;
}

const PageHelmet: FC<PageHelmetProps> = ({ title = "", children }) => {
  return (
    <Head>
      <title>Karn creative labs: {`${title}`}</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
      {children}
    </Head>
  );
};

export default PageHelmet;
